print("========================================")
print("   STUDENT INTRODUCTION ")
print("========================================")

full_name = input("Enter your Full Name: ")
age = input("Enter your Age: ")
city = input("Enter your City: ")
university = input("Enter your University: ")
department = input("Enter your Departement: ")
fav_pro_lan = input("Enter your Favorite programming language: ")
one_pro_goal = input("Enter your One programming goal: ")

print(f"\nMy name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study at {university}.")
print(f"My department is {department}.")
print(f"My favorite programming language is {fav_pro_lan}.")
print(f"My programming goal is to {one_pro_goal}.")
