print("+--------------------------------+")
print("|       AKIBA STUDENT CARD      |")
print("+--------------------------------+")

name = input("Enter your Student Name: ")
student_id = input("Enter your Student ID: ")
department = input("Enter your Department: ")
year = input("Enter your Year: ")
university = input("Enter your University: ")
phone = input("Enter your Phone Number: ")

print("\n+--------------------------------+")
print("|       AKIBA STUDENT CARD      |")
print("+--------------------------------+")
print(f"| Name: {name}              | ")
print(f"| ID: {student_id}          |")
print(f"| Department: {department}  |")
print(f"| Year: {year}              |")
print(f"| University: {university}  |")
print(f"| Phone: {phone}            |")
print("+--------------------------------+")